version: "3.8"
services:
  jenkins:  # Jenkins Container
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock 
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - 8093:8080
    privileged: true
    user: root 
    restart: unless-stopped

