
#??? ??
variables:
    # ???? ??? ??
    port: 8060

    #feurl
    feUri: http://localhost:3060

    #??????? ? url
    beUri: http://localhost:${variables.port}
    value: local

    #????? ????
server:
    port: ${variables.port}



spring:
    profiles:
        active:
            - local
    datasource:
#        url: jdbc:mysql://localhost:3306/drill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        url: jdbc:mysql://k9a106.p.ssafy.io:3308/drill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        username: root
        password: ssafy
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    jpa:
        hibernate:
            ddl-auto: update
        show_sql: true
        properties:
            hibernate:
                format_sql: true #?? ??? ???
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB

cloud:
    aws:
        s3:
            bucket: drill-video-bucket.bucket
        region:
            static: ap-northeast-2
            auto: false
        stack:
            auto: false
        credentials:
            access-key: AKIA32XVP6DSV5IHAI3U
            secret-key: 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

logging.level:
    org.hibernate.SQL : info

servlet:
    session:
        timeout: 300m