spring:
  config:
    activate:
      on-profile: dev

  datasource:

    url: jdbc:mysql://localhost:3306/drill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost # 로컬에서 테스트 할 때는 localhost, 아니면 redis로 사용
      port: 6379
      password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
