
#??? ??
variables:
    # ???? ??? ??
    port: 8060

    #feurl
    feUri: http://localhost:3060

    #??????? ? url
    beUri: http://localhost:${variables.port}
    value: local

    #????? ????
server:
    port: ${variables.port}



spring:
    profiles:
        active:
            - local
    datasource:
        url: jdbc:mysql://localhost:3306/drill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        username: root
        password: ssafy
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    jpa:
        hibernate:
            ddl-auto: update
        show_sql: true
        properties:
            hibernate:
                format_sql: true #?? ??? ???

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: f8ae067dc6798972969cd650aca79d01
                        client-secret: u8FZ07hOCRzzLlr2QbVgHVnp5MeCSSuo
                        redirect-uri: ${varialbles.beUri}/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        client-name: Kakao
                        scope:
                            - profile_nickname
                            - account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
    data:
        redis:
            host: localhost # 로컬에서 테스트 할 때는 localhost, 아니면 redis로 사용
            port: 6379
            password: 123456

logging.level:
    org.hibernate.SQL : info



servlet:
    session:
        timeout: 300m

social:
    client:
        kakao:
            rest-api-key: a21cb4cfd9c1a81b77614f1af356f2d1
            secret-key:
            #      redirect-uri: http://localhost:8082/api/user
            redirect-uri: http://localhost:8081/auth
            grant_type: authorization_code
